/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import dragDropContentTypes from "@retikolo/drag-drop-content-types/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import seo from "@strapi/plugin-seo/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import excelExport from "strapi-plugin-excel-export-2024/strapi-admin";
import redirects from "strapi-plugin-redirects/strapi-admin";
import translate from "strapi-plugin-translate/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "drag-drop-content-types": dragDropContentTypes,
    "strapi-cloud": strapiCloud,
    seo: seo,
    "users-permissions": usersPermissions,
    "excel-export": excelExport,
    redirects: redirects,
    translate: translate,
  },
});
